name: Build and test
on: [push, pull_request]

jobs:
  build-test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - uses: eessi/github-action-eessi@v3

    - name: Build in EESSI + EESSI-Extend
      run: |
        module load EESSI-extend
        eb --logtostdout easybuild/bcftools.eb
      shell: bash
